#!/bin/bash
# Hapus semua file dari commit Surya Driver

FILES=(
"arch/arm64/boot/dts/qcom/batterydata-M703-ATL-6000mah.dtsi"
"arch/arm64/boot/dts/qcom/batterydata-M703-PM7150B-ATL-5160mah.dtsi"
"arch/arm64/boot/dts/qcom/dsi-panel-nt36672c-huaxing-fhd-video.dtsi"
"arch/arm64/boot/dts/qcom/dsi-panel-nt36672c-tianma-fhd-video.dtsi"
"arch/arm64/boot/dts/qcom/haptic.dtsi"
"arch/arm64/boot/dts/qcom/touchscreen.dtsi"
"arch/arm64/include/asm/bootinfo.h"
"arch/arm64/kernel/bootinfo.c"
"drivers/gpu/drm/msm/dsi-staging/dsi_panel_mi.h"
"drivers/gpu/drm/msm/xiaomi_frame_stat.c"
"drivers/gpu/drm/msm/xiaomi_frame_stat.h"
"drivers/input/fingerprint/Kconfig"
"drivers/input/fingerprint/Makefile"
"drivers/input/fingerprint/fpc1020_tee.c"
"drivers/input/fingerprint/gf3208/Kconfig"
"drivers/input/fingerprint/gf3208/Makefile"
"drivers/input/fingerprint/gf3208/gf_spi.c"
"drivers/input/fingerprint/gf3208/gf_spi.h"
"drivers/input/fingerprint/gf3208/netlink.c"
"drivers/input/fingerprint/gf3208/platform.c"
"drivers/input/touchscreen/lct_tp_gesture.c"
"drivers/input/touchscreen/lct_tp_gesture.h"
"drivers/input/touchscreen/lct_tp_grip_area.c"
"drivers/input/touchscreen/lct_tp_grip_area.h"
"drivers/input/touchscreen/lct_tp_info.c"
"drivers/input/touchscreen/lct_tp_info.h"
"drivers/input/touchscreen/lct_tp_palm.c"
"drivers/input/touchscreen/lct_tp_palm.h"
"drivers/input/touchscreen/lct_tp_selftest.c"
"drivers/input/touchscreen/lct_tp_selftest.h"
"drivers/input/touchscreen/lct_tp_work.c"
"drivers/input/touchscreen/lct_tp_work.h"
"drivers/input/touchscreen/nt36xxx_spi/Kconfig"
"drivers/input/touchscreen/nt36xxx_spi/Makefile"
"drivers/input/touchscreen/nt36xxx_spi/nt36xxx.c"
"drivers/input/touchscreen/nt36xxx_spi/nt36xxx.h"
"drivers/input/touchscreen/nt36xxx_spi/nt36xxx_ext_proc.c"
"drivers/input/touchscreen/nt36xxx_spi/nt36xxx_fw_update.c"
"drivers/input/touchscreen/nt36xxx_spi/nt36xxx_mem_map.h"
"drivers/input/touchscreen/nt36xxx_spi/nt36xxx_mp_ctrlram.c"
"drivers/input/touchscreen/nt36xxx_spi/nt36xxx_mp_ctrlram.h"
"drivers/input/touchscreen/xiaomi/Kconfig"
"drivers/input/touchscreen/xiaomi/Makefile"
"drivers/input/touchscreen/xiaomi/xiaomi_touch.c"
"drivers/input/touchscreen/xiaomi/xiaomi_touch.h"
"drivers/misc/aw8624_haptic/Kconfig"
"drivers/misc/aw8624_haptic/Makefile"
"drivers/misc/aw8624_haptic/aw8624.c"
"drivers/misc/aw8624_haptic/aw8624.h"
"drivers/misc/aw8624_haptic/aw8624_reg.h"
"drivers/misc/drv2624_haptic/Default_param.c"
"drivers/misc/drv2624_haptic/Kconfig"
"drivers/misc/drv2624_haptic/Makefile"
"drivers/misc/drv2624_haptic/RTP_parser.c"
"drivers/misc/drv2624_haptic/RTP_parser.h"
"drivers/misc/drv2624_haptic/drv2624.c"
"drivers/misc/drv2624_haptic/drv2624.h"
"drivers/misc/drv2624_haptic/drv2624_parser_interfaces.h"
"drivers/misc/wl2866d.c"
"drivers/power/supply/maxim/Kconfig"
"drivers/power/supply/maxim/Makefile"
"drivers/power/supply/maxim/ds28e16.c"
"drivers/power/supply/maxim/ds28e16.h"
"drivers/power/supply/maxim/onewire_gpio.c"
"drivers/power/supply/maxim/onewire_gpio.h"
"drivers/power/supply/maxim/sha384_software.c"
"drivers/power/supply/maxim/sha384_software.h"
"drivers/power/supply/maxim/ucl_hash.h"
"drivers/power/supply/maxim/ucl_retdefs.h"
"drivers/power/supply/maxim/ucl_sha3.c"
"drivers/power/supply/maxim/ucl_sha3.h"
"drivers/power/supply/sc8551_charger.c"
"drivers/power/supply/sc8551_reg.h"
"drivers/power/supply/ti/Kconfig"
"drivers/power/supply/ti/Makefile"
"drivers/power/supply/ti/bq25970_reg.h"
"drivers/power/supply/ti/bq2597x_charger.c"
"drivers/power/supply/ti/cp_qc30.c"
"drivers/power/supply/ti/cp_qc30.h"
"drivers/power/supply/ti/pd_policy_manager.c"
"drivers/power/supply/ti/pd_policy_manager.h"
"drivers/soc/qcom/serial_num.c"
"include/drm/drm_notifier.h"
"include/misc/wl2866d.h"
)

for f in "${FILES[@]}"; do
    if [ -f "$f" ]; then
        echo "Deleting $f"
        rm -f "$f"
    fi
done

echo "Selesai menghapus semua file Surya Driver."
